image:
  repository: allinallacr.azurecr.io/backendpython
  tag: "main"

replicaCount: 1

ingress:
  host: backendpython-dev.example.com

pdb:
  enabled: true
  minAvailable: 1

config:
  azureOpenAiEndpoint: "https://foundryallinalldev007.services.ai.azure.com/openai/v1"
  azureModelName: "gpt-5.4-mini-deployment"
  azureApiKey: "REPLACE_WITH_ACTUAL_KEY_OR_USE_K8S_SECRET"
