apiVersion: v1
kind: ConfigMap
metadata:
  name: backendpython-config
  namespace: apps
data:
  VITE_AZURE_API_URL: "{{ .Values.config.azureApiUrl }}"
  VITE_AZURE_MODEL_NAME: "{{ .Values.config.azureModelName }}"
  VITE_AZURE_API_KEY: "{{ .Values.config.azureApiKey }}"
