apiVersion: v1
kind: ConfigMap
metadata:
  name: backendpython-config
  namespace: apps
data:
  AZURE_OPENAI_ENDPOINT: { { .Values.config.AZURE_OPENAI_ENDPOINT | quote } }
  AZURE_MODEL_NAME: { { .Values.config.AZURE_MODEL_NAME | quote } }
