apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: apps
data:
  VITE_AZURE_API_URL: { { .Values.config.azureApiUrl | quote } }
  VITE_AZURE_MODEL_NAME: { { .Values.config.azureModelName | quote } }
