apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespace }}
data:
  BACKEND_API_URL: "http://backendexpress:3000"
  ORCHESTRATOR_API_URL: "http://orchestrator:5000"
  AZURE_API_URL: {{ required "config.azureApiUrl is required" .Values.config.azureApiUrl | quote }}
  AZURE_MODEL_NAME: {{ required "config.azureModelName is required" .Values.config.azureModelName | quote }}