apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: { { .Values.namespace | default "apps" } }
data:
  VITE_AZURE_API_URL:
    {
      {
        required "config.azureApiUrl is required" .Values.config.azureApiUrl | quote,
      },
    }
  VITE_AZURE_MODEL_NAME:
    {
      {
        required "config.azureModelName is required" .Values.config.azureModelName | quote,
      },
    }
