apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:main
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
