apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-deployment
  namespace: apps
  labels:
    app: apps

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: apps

  template:
    metadata:
      labels:
        app: apps
        workload: apps

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apps
                topologyKey: kubernetes.io/hostname

      nodeSelector:
        workload: apps

      tolerations:
        - key: workload
          operator: Equal
          value: apps
          effect: NoSchedule

      containers:
        - name: apps-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: VITE_AZURE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_AZURE_API_URL

            - name: VITE_AZURE_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_AZURE_MODEL_NAME

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
