### Say Hello
GET https://2p796oxvp2.execute-api.eu-north-1.amazonaws.com/prod/sayhello1

###

POST https://2p796oxvp2.execute-api.eu-north-1.amazonaws.com/prod/sayhello
Content-Type: application/json

{
    "name": "John"
}