resources:
  - ../../base

replicas:
  - name: frontend
    count: 1

images:
  - name: frontend-image
    newName: acrallinalldev.azurecr.io/frontend
    newTag: dev

patches:
  - target:
      kind: Ingress
      name: frontend-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.all-in-all.example.com
