on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - "k8s/**"
      - ".github/workflows/frontend-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: cloudquicklabs.azureacr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t cloudquicklabs.azureacr.io/frontend:${{ github.sha }}
          docker push cloudquicklabs.azureacr.io/frontend:${{ github.sha }}
